spring:
  kafka:
    producer:
      producer1:
       bootstrap-servers: localhost:9092
       key-serializer: org.apache.kafka.common.serialization.StringSerializer
       value-serializer:  org.springframework.kafka.support.serializer.JsonSerializer
       properties:
         partitioner.class: com.mfouad.kafkaprod.partions.FloorPartioner
      producer2:
       bootstrap-servers: localhost:9092
       key-serializer: org.apache.kafka.common.serialization.StringSerializer
       value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer


topic:
  avro:
   name: avro-topic
  name: floor
  id: 24343dg
  wiki:
    name: wikiTopic
    partitions: 3
  partitions: 2




